export const bookmark = [
    {
        id: 1,
        data: "bookmark",
        type: "black",
        category: "закладка",
        title: "черная закладка",
        text: "пластиковая односторонняя закладка для книг",
        price: 300,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/bookmark/black/1.jpg"],
    },
    {
        id: 2,
        data: "bookmark",
        type: "blue",
        category: "закладки",
        title: "синяя закладка",
        text: "пластиковая односторонняя закладка для книг",
        price: 300,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/bookmark/blue/1.jpg"],
    },
];
export const pin = [
    {
        id: 3,
        data: "pin",
        type: "pin1",
        category: "значки",
        title: "пин",
        text: "пин из эпоксидной смолы с жёлтой застёжкой-сердечком",
        price: 250,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/pin/pin1/1.jpg","../../assets/data/pin/pin1/2.jpg"],
    },
];
export const postcard = [
    {
        id: 4,
        data: "postcard",
        type: "date",
        category: "открытки",
        title: "свидание",
        text: "односторонняя печать. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/date/1.jpg"],
    },
    {
        id: 5,
        data: "postcard",
        type: "dont",
        category: "открытки",
        title: "не потеряй себя",
        text: "односторонняя печать. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/dont/1.jpg"],
    },
    {
        id: 6,
        data: "postcard",
        type: "flowers",
        category: "открытки",
        title: "цветы",
        text: "двусторонняя печать, на обороте место для тёплых слов. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/flowers/1.jpg"],
    },
    {
        id: 7,
        data: "postcard",
        type: "june",
        category: "открытки",
        title: "июнь",
        text: "односторонняя печать. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/june/1.jpg"],
    },
    {
        id: 8,
        data: "postcard",
        type: "mind",
        category: "открытки",
        title: "мысли",
        text: "односторонняя печать. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/mind/1.jpg"],
    },
    {
        id: 9,
        data: "postcard",
        type: "ticket",
        category: "открытки",
        title: "билет в один конец",
        text: "односторонняя печать. текстурная бумага плотностю 250 гр. формат А6",
        price: 100,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/postcard/ticket/1.jpg"],
    },
];
export const stickers = [
    {
        id: 10,
        data: "stickers",
        type: "a6",
        offtype: "flowers",
        category: "стикеры А6",
        title: "цветы",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. формат А6",
        price: 130,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/a6/flowers/1.jpg"],
    },
    {
        id: 11,
        data: "stickers",
        type: "a6",
        offtype: "neer",
        category: "стикеры А6",
        title: "я всегда буду рядом",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. формат А6",
        price: 130,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/a6/neer/1.jpg"],
    },
    {
        id: 12,
        data: "stickers",
        type: "a6",
        offtype: "ocean",
        category: "стикеры А6",
        title: "океан",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. формат А6",
        price: 130,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/a6/ocean/1.jpg"],
    },
    {
        id: 13,
        data: "stickers",
        type: "a6",
        offtype: "sleep",
        category: "стикеры А6",
        title: "лавандовый сон",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. формат А6",
        price: 130,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/a6/sleep/1.jpg", "../../assets/data/stickers/a6/sleep/2.jpg"],
    },
    {
        id: 14,
        data: "stickers",
        type: "a6",
        offtype: "summer",
        category: "стикеры А6",
        title: "лето",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. формат А6",
        price: 130,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/a6/summer/1.jpg", "../../assets/data/stickers/a6/summer/2.jpg", "../../assets/data/stickers/a6/summer/3.jpg"],
    },
    {
        id: 15,
        data: "stickers",
        type: "little",
        offtype: "copybook",
        category: "стикеры поменьше",
        title: "тетрадь в клеточку",
        text: "стикеры по книге Микиты Франко 'тетрадь в клеточку'. материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. размер 10*10см",
        price: 110,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/little/copybook/1.jpg"],
    },
    {
        id: 16,
        data: "stickers",
        type: "little",
        offtype: "life",
        category: "стикеры поменьше",
        title: "дни нашей жизни",
        text: "стикеры по книге Микиты Франко 'дни нашей жизни'. материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. размер 10*10см",
        price: 110,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/little/life/1.jpg"],
    },
    {
        id: 17,
        data: "stickers",
        type: "little",
        offtype: "mini",
        category: "стикеры поменьше",
        title: "стикеры малыши",
        text: "материал: виниловая плёнка с матовой ламинацией. размер 5*5см",
        price: 30,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/little/mini/1.jpg"],
    },
    {
        id: 18,
        data: "stickers",
        type: "little",
        offtype: "soul",
        category: "стикеры поменьше",
        title: "нежность души",
        text: "материал: виниловая плёнка с матовой ламинацией. вырубка по форме каждого стикера. размер 7*7см",
        price: 50,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/stickers/little/soul/1.jpg"],
    },
];
export const trinket = [
    {
        id: 19,
        data: "trinket",
        type: "trinket1",
        category: "брелки",
        title: "брелок",
        text: "акриловый брелок с карабином-звёздочкой",
        price: 350,
        discount: false,
        hot: false,
        new: false,
        images: ["../../assets/data/trinket/trinket1/1.jpg"],
    },
]